---
- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: creating nginx configuration in /sites-available
  copy:
    source: nginx_mind_ease.conf
    dest: /etc/nginx/etc/nginx/sites-available/mind-ease.me
    state: link

- name: creating nginx configuration in /sites-enabled
  copy:
    source: nginx_mind_ease.conf
    dest: /etc/nginx/etc/nginx/sites-enabled/mind-ease.me
    state: link

# We put robs code here?


