---
- name: Install MariaDB
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: mariadb
    enabled: yes

- name: Start service mariadb, if not started
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Ensure Python and pip are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-pymysql
    state: present
    update_cache: yes

#### Code below was taken/modified from geerlinguy (https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/secure-installation.yml)
- name: Set root user to password
  mysql_user:
    login_host: linux_host
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: 'comsc'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  become: yes


## Has to be after the password assignment, for idempotency.
#- name: Copy user-my.cnf file with password credentials.
#  ansible.builtin.template:
#    src: "user-my.cnf.j2"
#    dest: "{{ mysql_user_home }}/.my.cnf"
#    owner: "{{ mysql_user_name }}"
#    mode: 0600
#  no_log: "{{ mysql_hide_passwords }}"
#  when: >
#    mysql_user_name != mysql_root_username
#
#    and (mysql_install_packages | bool or mysql_user_password_update)
#
## Has to be after the root password assignment, for idempotency.
#- name: Copy .my.cnf file with root password credentials.
#  ansible.builtin.template:
#    src: "root-my.cnf.j2"
#    dest: "{{ mysql_root_home }}/.my.cnf"
#    owner: root
#    group: root
#    mode: 0600
#  no_log: "{{ mysql_hide_passwords }}"
#  when: mysql_install_packages | bool or mysql_root_password_update


#- name: Remove MySQL test database.
#  mysql_db:
#    name: 'test'
#    state: absent