---
- name: Install MariaDB
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: mariadb
    enabled: yes

- name: Start service mariadb, if not started
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Ensure Python and pip are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-pymysql
    state: present
    update_cache: yes


- name: create database towns
  community.mysql.mysql_db:
    login_host: "{{ db_host }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
    name:
      - "{{ db_name }}"
    state: present
  run_once: true

- name: Import schema.sql
  community.mysql.mysql_db:
    login_host: "{{ db_host }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
    name: "{{ db_name }}"
    state: import
    target: '{{ schema_towns_file }}'

- name: Import data.sql
  community.mysql.mysql_db:
    login_host: "{{ db_host }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
    name: "{{ db_name }}"
    state: import
    target: '{{ data_towns_file }}'

#- name: Set root user to password
#  mysql_user:
#    login_host: linux_host
#    login_unix_socket: /run/mysqld/mysqld.sock
#    login_user: 'root'
#    login_password: ''
#    name: '{{ mysql_root_username }}'
#    password: '{{ mysql_root_password }}'
#    state: present
#  run_once: true



  become: yes
