---
- import_tasks: install.yml

- include_tasks: webroot_cert_creation.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'webroot'
  loop_control:
    loop_var: cert_item

- include_tasks: standalone_cert_creation.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- import_tasks: cronjob_renew.yml
  when: certbot_auto_renew





